---
title: "Objetos"
author: "http://synergy.vision/"
output: 
  html_document:
    self_contained: false

---

```{r setup, include=FALSE}
tutorial::go_interactive()
```

# Creación de objetos

```{r tut=TRUE,ex="create_a2", type="pre-exercise-code"}
b <- 5
```

```{r tut=TRUE,ex="create_a2", type="sample-code"}
# Crea una variable a, igual a 5

# Crea una variable n, igual a 25

# Muestra el valor de a y de n


# Muestre el valor de b

```

```{r tut=TRUE,ex="create_a2", type="solution"}
# Crea una variable a, igual a 5
a<-5
# Crea una variable n, igual a 25
n<-25
# Muestra el valor de a y de n
a
n
# Muestre el valor de b
b
```

```{r tut=TRUE,ex="create_a2", type="sct"}
test_object("a")
test_object("n")
test_object("b")
test_output_contains("a", incorrect_msg = "Asegurate de mostrar el valor de `a`.")
test_output_contains("n", incorrect_msg = "Asegurate de mostrar el valor de `n`.")
test_output_contains("b", incorrect_msg = "Asegurate de mostrar el valor de `b`.")
success_msg("Excelente!")
```

# Función ls()

```{r tut=TRUE, ex="ls", type="sample-code"}
name <- "Carmen"
n1 <- 10
n2 <- 100
m <- 0.5

ls()
```

```{r tut=TRUE, ex="ls", type="sct"}
test_error()
success_msg("Muy bien")
```

# Función ls.str()

```{r tut=TRUE, ex="play_around", type="pre-exercise-code"}
a<-5
b<-5
n<-25
name <- "Carmen"
n1 <- 10
n2 <- 100
m <- 0.5
```

```{r tut=TRUE, ex="play_around", type="sample-code"}
ls.str()
```


```{r tut=TRUE, ex="play_around", type="sct"}
test_error()
success_msg("Buen trabajo")
```

# Función rm()

```{r tut=TRUE, ex="delete", type="pre-exercise-code"}
name <- "Carmen"
n1 <- 10
n2 <- 100
m <- 0.5
```

```{r tut=TRUE, ex="delete", type="sample-code"}
# Borrar de memoria el objeto n1

# Liste los objetos en memoria

```

```{r tut=TRUE, ex="delete", type="solution"}
# Borrar de memoria el objeto n1
rm(n1)

# Liste los objetos en memoria
ls()

```

```{r tut=TRUE, ex="delete", type="sct"}
test_output_contains("rm(n1)", incorrect_msg = "Asegurate de borrar el objeto correcto.")
test_function("rm")
test_output_contains("ls()", incorrect_msg = "Asegurese de llamar a la función ls() correctamente")
test_function("ls")
test_error()
success_msg("Bien!")
```

# Función paste()

```{r tut=TRUE, ex="paste", type="sample-code"}
cart_1 <- 'Mi'
cart_2 <- 'primera'
cart_3 <- 'Cadena de caracteres'
# Guarde en c el carácter formado por cart_1, 
# cart_2, cart_3 utilizando la función paste() 
# utilice el argumento sep =" "

# Imprima c

```

```{r tut=TRUE, ex="paste", type="solution"}
cart_1 <- 'Mi'
cart_2 <- 'primera'
cart_3 <- 'Cadena de caracteres'
# Guarde en c el carácter formado por cart_1, 
# cart_2, cart_3 utilizando la función paste()
# utilice el argumento sep =" "
c<- paste(cart_1, cart_2, cart_3, sep = " ")
# Imprima c
c
```

```{r tut=TRUE, ex="paste", type="sct"}
test_function("paste")
test_output_contains("paste()", incorrect_msg = "Recuerda usar la función paste().")
test_object("c")
test_output_contains("c", incorrect_msg = "Recuerde llamar `c` a la variable")
success_msg("Bien!")
```
